### ISSUE TITLE
All tests should be independent

### ISSUE THREAD

**Issue by mythmon** [mozilla/share-button-study#27]
Tests should be able to run in arbitrary order and in isolation. The second test here seems to rely on the first test.

[source](https://github.com/marcrowo/share-button-study/blob/680e8aecd097ec65e96c79d8739bcfafc4a6ea3f/test/button_test.js#L105-L116)

```js
// ADDON UNINSTALLED
it("should no longer trigger animation once uninstalled", async() => {
  await utils.uninstallAddon(driver, addonId);
  await utils.copyUrlBar(driver);
  const { hasClass, hasColor } = await utils.testAnimation(driver);
  assert(!hasClass && !hasColor);
});

it("should no longer trigger popup once uninstalled", async() => {
  await utils.copyUrlBar(driver);
  assert(!(await utils.testPanel(driver)));
});
```

**Comment by marcrowo** [comment]
Would it be sufficient to store whether the addon has been uninstalled at the start of both tests, and uninstall if this is not the case? 
ie. `if (!addonUninstalled) { uninstallAddon(); }`

**Comment by marcrowo** [comment]
Also, these tests do not navigate to a "regular page", so the test will pass if run in isolation, even if the addon is uninstalled.

**Comment by marcrowo** [comment]
After discussion with @mythmon, maybe the best idea is to use a new `describe` to encompass these tests. Describes can also be nested.
- `beforeEach()`: uninstall the addon
- `afterEach()`: install addon

Then, at the start of each test we can assume the addon is installed. We need to uninstall to run the test.
